// <auto-generated />
using System;
using Global_Solution.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Global_Solution.Migrations
{
    [DbContext(typeof(OracleDBContext))]
    [Migration("20231117133041_Initial01")]
    partial class Initial01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Global_Solution.Models.cy_consulta_medica", b =>
                {
                    b.Property<int>("IdConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConsulta"));

                    b.Property<DateTime?>("dataConsulta")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("diagnostico")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("prescricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("sintomas")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdConsulta");

                    b.ToTable("cy_consulta_medica");
                });

            modelBuilder.Entity("Global_Solution.Models.cy_especialidade_medica", b =>
                {
                    b.Property<int>("IdEspecialidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEspecialidade"));

                    b.Property<string>("nomeEspecialidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdEspecialidade");

                    b.ToTable("cy_especialidade_medica");
                });

            modelBuilder.Entity("Global_Solution.Models.cy_feedbacks", b =>
                {
                    b.Property<int>("IdFeedback")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFeedback"));

                    b.Property<int>("classificacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("comentario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdFeedback");

                    b.ToTable("cy_feedbacks");
                });

            modelBuilder.Entity("Global_Solution.Models.cy_historico_medico", b =>
                {
                    b.Property<int>("IdHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorico"));

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("dataEvento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdHistorico");

                    b.ToTable("cy_historico_medico");
                });

            modelBuilder.Entity("Global_Solution.Models.cy_hospitais", b =>
                {
                    b.Property<int>("IdHospital")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHospital"));

                    b.Property<string>("cep")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("nomeHospital")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdHospital");

                    b.ToTable("cy_Hospitais");
                });

            modelBuilder.Entity("Global_Solution.Models.cy_mensagens", b =>
                {
                    b.Property<int>("idMensagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMensagem"));

                    b.Property<int>("Destinatario")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Remetente")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("dataEnvio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("lida")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("idMensagem");

                    b.ToTable("cy_Mensagens");
                });

            modelBuilder.Entity("Global_Solution.Models.cy_notificacoes", b =>
                {
                    b.Property<int>("IdNotificacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacao"));

                    b.Property<DateTime?>("dataEnvio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("lida")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("mensagem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdNotificacao");

                    b.ToTable("cy_Notificacoes");
                });

            modelBuilder.Entity("Global_Solution.Models.cy_pagamentos", b =>
                {
                    b.Property<int>("IdPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPagamento"));

                    b.Property<DateTime>("dataPagamento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("informacoesCartao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<float>("valor")
                        .HasColumnType("BINARY_FLOAT");

                    b.HasKey("IdPagamento");

                    b.ToTable("cy_Pagamentos");
                });

            modelBuilder.Entity("Global_Solution.Models.cy_prescricao_medica", b =>
                {
                    b.Property<int>("IdPrescricao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrescricao"));

                    b.Property<string>("Medicamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("dataPrescricao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("dosagem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("instrucoes")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdPrescricao");

                    b.ToTable("cy_Prescricao_Medicas");
                });

            modelBuilder.Entity("Global_Solution.Models.cy_profissionais_saude", b =>
                {
                    b.Property<int>("IdProfissional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProfissional"));

                    b.Property<string>("RegistroMedico")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("especialidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdProfissional");

                    b.ToTable("cy_Profissionais_Saudes");
                });

            modelBuilder.Entity("Global_Solution.Models.cy_usuarios", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<int?>("cy_profissionais_saudeIdProfissional")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("dataNascimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("sexo")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("cy_profissionais_saudeIdProfissional");

                    b.ToTable("cy_Usuarios");
                });

            modelBuilder.Entity("Global_Solution.Models.cy_usuarios", b =>
                {
                    b.HasOne("Global_Solution.Models.cy_profissionais_saude", null)
                        .WithMany("IdUsuario")
                        .HasForeignKey("cy_profissionais_saudeIdProfissional");
                });

            modelBuilder.Entity("Global_Solution.Models.cy_profissionais_saude", b =>
                {
                    b.Navigation("IdUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
