// <auto-generated />
using System;
using Global_Solution.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Global_Solution.Migrations
{
    [DbContext(typeof(OracleDBContext))]
    partial class OracleDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity<cy_consulta_medica>(b =>
            {
                b.Property<int>("IdConsulta")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConsulta"));

                b.Property<DateTime?>("dataConsulta")
                    .HasColumnType("TIMESTAMP(7)");

                b.Property<string>("descricao")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("diagnostico")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("prescricao")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("sintomas")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("status")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.HasKey("IdConsulta");

                b.ToTable("cy_consulta_medica");
            });

            modelBuilder.Entity<cy_especialidade_medica>(b =>
            {
                b.Property<int>("IdEspecialidade")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEspecialidade"));

                b.Property<string>("nomeEspecialidade")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.HasKey("IdEspecialidade");

                b.ToTable("cy_especialidade_medica");
            });

            // Continue adicionando outras entidades da mesma maneira...

#pragma warning restore 612, 618
        }
    }
}
